main:
# optional configuration
  # total map area
  map:
   # start: 0x20000000
    #end:   0x20004000
    x: 30
    y: 30
    size_x: 200
    size_y: 700
  # starting addresses of the sections to parse [optional]
  address:
    highest: 0x20008000
    lowest: 0x20000000
  # size in bytes of the sections to parse [optional]
  size:
    max: 100000
    min: 100

zoomed:
  - map:
      x: 500
      y: 30
      size_x: 300
      size_y: 1200
      end: 0x20002000
    # starting addresses of the sections to parse [optional]
    address:
      highest: 0x20002000
      lowest: 0x20001000
    # size in bytes of the sections to parse [optional]
    size:
      max: 100000
      #min: 100

  - map:
      x: 1000
      y: 30
      size_x: 300
      size_y: 1200
      end: 0x20003ac8
      start: 0x20002000

    # starting addresses of the sections to parse [optional]
    address:
      highest: 0x20003ac8
      lowest: 0x20002000
    # size in bytes of the sections to parse [optional]
    size:
      max: 100000
      #min: 100
links:
  force: true
  addresses: [0x20001000,0x20003ac8, 0x20002000]
  sections: []



