variables:
  graphite: &graphite '#2A363B'
  pastel_green: &pastel_green '#99B898'
  pastel_yellow: &pastel_yellow '#FECEA8'
  pastel_orange: &pastel_orange '#FF847C'
  pastel_red: &pastel_red '#E84A5F'

style:
  text-fill: 'lightgrey'
  break-size: 60
  break-type: '~'
  growth-arrow-size: 2
  growth-arrow-fill: 'white'
  growth-arrow-stroke: 'black'
  background: *graphite
  fill: '#99B898'

  stroke: *graphite
  stroke-width: 1
  text-stroke: 'black'
  text-stroke-width: 0
  size: '16'
  font_size: '16'
  font_type: 'Helvetica Bold'
  weight: '16'

areas:
# total area area
- area:
    title: 'Full Memory Map'
    # start and end addresses are optional
    # They can be specified to force drawing a region
    # that doesn't contain any segments
    # start: 0x20000000
    # end:   0x20004000

    # Specify the position of the area and its size here
    pos: [30, 50]
    size: [300, 900]
    # starting addresses of the sections to parse
    range: [0x0, 0x100000000]
    # Maximum and minimum size in bytes of the sections to parse
    section-size: [0x02F00000]

    style:
      fill: *pastel_green
      growth-arrow-fill: 'black'
      growth-arrow-size: 0.6
      growth-arrow-stroke: 'black'
    sections:
    - names: [ External Device ]
      fill: '#FF847C'
      flags: grows-up, hide-size, hide-address
      style:
        hide-size: true
        hide-address: true

- area:
    pos: [ 500, 30 ]
    size: [ 200, 200 ]
    range: [0xE8040000, 0xE8044000]
    sections: # Adding the 'regions' sub-level under 'style'
    - names: [ ROM Table ]
      style:
        fill: *pastel_green
    - names: [ External PPB ]
      style:
        fill: *pastel_yellow
    - names: [ ETM, Peripheral ]
      style:
        fill: *pastel_orange
    - names: [ TPIU ]
      style:
        fill: *pastel_red

- area:
    pos: [ 500, 280 ]
    size: [ 200, 400 ]
    range: [0xE0000000, 0xE00F0000]
    style:
      stroke-width: 1
    sections:
    - names: [ Reserved ]
      flags: grows-down, break
    - names: [ DWT ]
      style:
        hide-size: true
        hide-address: true
        hide-name: true
    labels:
      - address: 0xe0017FFF
        text: Random name
        length: 30
        directions: right
        style:
          stroke: *pastel_green
          stroke-width: 1
          stroke-dasharray: '3,3'
          weigth: 1
          text_fill: *pastel_green
      - address: 0xe0014FFF
        text: Cool section
        length: 30
        directions: right
        style:
          stroke: *pastel_green
          stroke-width: 2
          stroke-dasharray: '2,2'
          weigth: 1
          text_fill: *pastel_green
      - address: 0xe8041000
        text: Cool Memory


- area:
    pos: [ 500, 730 ]
    size: [ 200, 200 ]
    range: [0x40000000, 0x43000000]
    sections: # Adding the 'regions' sub-level under 'style'
    - names: [ Bit ]
      style:
        fill: *pastel_yellow
    - names: [ Bit band region ]
      style:
        fill: *pastel_orange
    - names: [ Reserved ]
      flags: grows-down, break

- area:
    pos: [ 500, 980 ]
    size: [ 200, 200 ]
    range: [0x20000000, 0x23000000]

links:
  style:
    stroke: 'lightgray'
    stroke-width: 1
    fill: 'gray'

  addresses: [ 0x20000000,
               0x23000000,
               0x40000000,
               0x43000000,
               0xE0000000,
               0xE00F0000,
               0xE8040000,
               0xE8044000,
               0xe00e0000
  ]

  sections: [
    ['TPIU', 'ROM Table'],
    ['ITM', 'NVIC'],
    ['Bit band region', 'Bit band alias'],
    ['Bit band region', 'Bit band alias']]

size: [1000, 1000]


