style:
  label_font: 'Helvetica Bold'
  label_size: '16px'
  label_stroke_width: 0.5px
  link_stroke_color: 'grey'
  link_stroke_width: 1
  map_background_color: 'lightgrey'
  section_stroke_width: 1

maps:
# total map area
- map:
    # start and end addresses are optional
    # They can be specified to force drawing a region
    # that doesn't contain any segments
    # start: 0x20000000
    # end:   0x20004000

    # Specify the position of the map and its size here
    x: 30
    y: 30
    size_x: 100
    size_y: 400

    # starting addresses of the sections to parse
    address:
      min: 0x0
      max: 0x200000000

    # Maximum and minimum size in bytes of the sections to parse
    size:
      max: 100000
      #min: 10000

- map:
    start: 0x8000000
    end:   0x8008000
    x: 250
    y: 30
    size_x: 200
    size_y: 700

    # FLASH:
    address:
      min: 0x8000000
      max: 0x8008000
    # size in bytes of the sections to parse [optional]
    size:
      min: 0x200
    style:
      label_color: 'darkblue'

- map:
    x: 600
    y: 30
    size_x: 200
    size_y: 500

    # RAM:
    address:
      min: 0x20000000
      max: 0x20002000
    # size in bytes of the sections to parse [optional]
    size:
      max: 1000000
    style:
        section_stroke_color: 'darkgreen'
        section_fill_color: 'lightgreen'
        label_color: 'green'

links:
  force: true
  addresses: [ 0x80045d4, 0x20000910, 0x200002e8]
  sections: [HAL_RCC_OscConfig, __malloc_av_]



