style:
  break-size: 60
  break-type: '~'
  label-font: 'Helvetica Bold'
  label-color: 'lightgrey'
  label-size: '16'
  label-stroke-width: 0
  link-stroke-color: 'grey'
  link-fill-color: 'grey'
  link-stroke-width: 1
  link-opacity: 0.5
  area-background-color: 'none'
  section-stroke-width: 1
  section-fill-color: '#99B898'
  section-stroke-color: '#2A363B'
  #section-stroke-color: 'white'
  background-color: '#2A363B'

areas:
# total area area
- area:
    # start and end addresses are optional
    # They can be specified to force drawing a region
    # that doesn't contain any segments
    # start: 0x20000000
    # end:   0x20004000

    # Specify the position of the area and its size here
    x: 30
    y: 30
    size-x: 300
    size-y: 900

    # starting addresses of the sections to parse
    address:
      min: 0x0
      max: 0x100000000

    # Maximum and minimum size in bytes of the sections to parse
    size:
      min: 0x02F00000
    style:
      overrrides:
      - sections: [ Peripheral ]
        section-fill-color: '#FF847C'

- area:
    x: 500
    y: 30
    size-x: 200
    size-y: 200

    address:
      min: 0xE8040000
      max: 0xE8044000
    style:
      link-stroke_color: 'grey'
      link-stroke_width: 0
      section-stroke_width: 1
      overrrides: # Adding the 'regions' sub-level under 'style'
        - sections: [ ROM Table ]
          section-fill_color: '#99B898'
        - sections: [ External PPB ]
          section-fill_color: '#FECEA8'
        - sections: [ ETM, Peripheral ]
          section-fill_color: '#FF847C'
        - sections: [ TPIU ]
          section-fill_color: '#E84A5F'

- area:
    x: 500
    y: 280
    size-x: 200
    size-y: 400

    address:
      min: 0xE0000000
      max: 0xE00F0000

    style:
      link-stroke-color: 'grey'
      link-stroke-width: 1
      section-stroke-width: 1

- area:
    x: 500
    y: 730
    size-x: 200
    size-y: 200

    address:
      min: 0x40000000
      max: 0x43000000
    style:
      overrrides: # Adding the 'regions' sub-level under 'style'
        - sections: [ Bit ]
          section-fill_color: '#FECEA8'
        - sections: [ Bit band region ]
          section-fill_color: '#FF847C'

- area:
    x: 500
    y: 980
    size-x: 200
    size-y: 200

    address:
      min: 0x20000000
      max: 0x23000000

links:
  force: true
  addresses: [ 0x20000000,
               0x23000000,
               0x40000000,
               0x43000000,
               0xE0000000,
               0xE00F0000,
               0xE8040000,
               0xE8044000,
               0xe00e0000
  ]
  sections: [
    ['TPIU', 'ROM Table'],
    ['ITM', 'NVIC'],
    ['Bit band region', 'Bit band alias'],
    ['Bit band region', 'Bit band alias']]

map:
- address: 0xE0030000
  name: Reserved
  type: section
  flags: break, hide-label, hide-address
- name: NVIC
  flags: hide-address, hide-name




