style:
  break-size: 60
  break-type: '~'
  label-font: 'Helvetica Bold'
  label-color: 'lightgrey'
  label-size: '16'
  label-stroke-width: 0
  link-stroke-color: 'grey'
  link-fill-color: 'grey'
  link-stroke-width: 1
  link-opacity: 0.5
  area-background-color: 'none'
  section-stroke-width: 1
  section-fill-color: '#99B898'
  section-stroke-color: '#2A363B'
  #section-stroke-color: 'white'
  background-color: '#2A363B'
  growth-arrow-weight: 1
  growth-arrow-stroke-color: 'black'
  growth-arrow-fill-color: 'white'

  fill: '#99B898'
  stroke: '#2A363B'
  stroke-width: 1
  size: '16'
  font_size: '16'
  font_type: 'Helvetica Bold'
  weight: '16'

areas:
# total area area
- area:
    # start and end addresses are optional
    # They can be specified to force drawing a region
    # that doesn't contain any segments
    # start: 0x20000000
    # end:   0x20004000

    # Specify the position of the area and its size here
    pos: [30, 30]
    size: [300, 900]
    # starting addresses of the sections to parse
    range: [0x0, 0x100000000]
    # Maximum and minimum size in bytes of the sections to parse
    section-size: [0x02F00000]


    style:
      stroke-width: 3

    sections:
    - names: [ Peripheral ]
      fill: '#FF847C'

- area:

    pos: [ 500, 30 ]
    size: [ 200, 200 ]
    range: [0xE8040000, 0xE8044000]

    style:

    sections: # Adding the 'regions' sub-level under 'style'
    - names: [ ROM Table ]
      style:
        fill: '#99B898'
    - names: [ External PPB ]
      style:
        fill: '#FECEA8'
    - names: [ ETM, Peripheral ]
      style:
        fill: '#FF847C'
    - names: [ TPIU ]
      style:
        fill: '#E84A5F'

- area:
    pos: [ 500, 280 ]
    size: [ 200, 400 ]
    range: [0xE0000000, 0xE00F0000]
    style:
      stroke-width: 1
    sections:
    - names: [ Reserved ]
      flags: grows-down, break

- area:
    pos: [ 500, 730 ]
    size: [ 200, 200 ]
    range: [0x40000000, 0x43000000]

    style:
    sections: # Adding the 'regions' sub-level under 'style'
    - names: [ Bit ]
      fill: '#FECEA8'
    - names: [ Bit band region ]
      fill: '#FF847C'
    - names: [ Reserved ]
      flags: grows-down, break

- area:
    pos: [ 500, 980 ]
    size: [ 200, 200 ]
    range: [0x20000000, 0x23000000]

links:
  style:
    stroke: 'blue'
    stroke-width: 1

  force: true
  addresses: [ 0x20000000,
               0x23000000,
               0x40000000,
               0x43000000,
               0xE0000000,
               0xE00F0000,
               0xE8040000,
               0xE8044000,
               0xe00e0000
  ]
  sections: [
    ['TPIU', 'ROM Table'],
    ['ITM', 'NVIC'],
    ['Bit band region', 'Bit band alias'],
    ['Bit band region', 'Bit band alias']]



