size: [800,900]
variables:
  graphite: &graphite '#2A363B'
  pastel_green: &pastel_green '#99B898'
  pastel_yellow: &pastel_yellow '#FECEA8'
  pastel_orange: &pastel_orange '#FF847C'
  pastel_red: &pastel_red '#E84A5F'

style:
  text-fill: 'lightgrey'
  break-size: 60
  break-type: '~'
  growth-arrow-size: 2
  growth-arrow-fill: 'white'
  growth-arrow-stroke: 'black'
  background: *graphite
  fill: '#99B898'

  stroke: *graphite
  stroke-width: 1
  text-stroke: 'black'
  text-stroke-width: 0
  font_type: 'Helvetica'

areas:
# total area area
- area:
    range: [0x0, 0x100000000]
    size: [200, 700]
    style:
      fill: *pastel_green
      hide-size: true
    sections:
      - names: [none]
        style:
          hide-name: true
          fill: grey

- area:
    range: [0x40000000, 0x40030000]
    pos: [500]
    size: [200, 700]
    style:
      fill: *pastel_green
      background: grey
      hide-size: true
    sections:
      - names: [none]
        style:
          hide-name: true
          fill: grey

links:
  style:
    fill: grey
  sections: [[TIM2, CRC]]


